on:
  push:
  workflow_dispatch:
    inputs:
      size:
        description: The size
        required: true
        default: medium
        type: choice
        options:
          - small
          - medium
          - large

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Check TypeScript types
        run: npm run check-types
  hello-world:
    runs-on: ubuntu-latest
    name: Say hello
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Print hello world
        id: hello
        uses: ./
        with:
          who-to-greet: 'Bob'
      - name: Print time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    environment: dev
    needs: [hello-world]
    steps:
      - name: Print env
        run: echo "Env is ${{ vars.APP_ENV }}"
