on:
  push:
  workflow_dispatch:
    inputs:
      size:
        description: The size
        required: true
        default: medium
        type: choice
        options:
          - small
          - medium
          - large

jobs:
  hello-world:
    runs-on: ubuntu-latest
    name: Say hello
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Print hello world
        id: hello
        uses: ./
        with:
          who-to-greet: 'Bob'
      - name: Print time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
      - name: Print env
        run: echo $APP_ENV
